### ISSUE TITLE
datetime-flux example action methods are not called

### ISSUE THREAD

**Issue by svnm** [goatslacker/iso#10]
It seems in the datetime-flux example when you call an action like `TimeActions.setAsync(Date.now())` it pretty much jumps straight into the store method ignoring the action. So rather than jumping in to the `setAsync(n)` function in TimeActions it goes directly to `onSetAsync(n)` in TimeStore.

Is this expected behaviour? because I was trying to make a similar example based on this one using images in a slider, and it seems like making an async call to get images in the action, similar to the `setAsync(n)` function basically skips the action part.

**Comment by goatslacker** [comment]
onSetAsync isn't supposed to get called until there is a dispatch which happens after the setTimeout resolves

**Comment by svnm** [comment]
In the example, `setAsync` is never called, so I change the method `updateTime()` in the MyReactComponent to call it, but it ignores the delay and just jumps straight to the store method `onSetAsync`. This is a bit of an issue, because I often make ajax calls to update data in the actions, then send the data to the store, which is synchronous. Thanks for helping by the way, I want to use this to set up a few alt/iso examples.

**Comment by svnm** [comment]
for instance, if I put a `console.log('action displatching...')` in any action method, it never shows the log

**Comment by svnm** [comment]
This could probably be closed now, as the example is in the https://github.com/goatslacker/isomorphic-react-examples so could be raised there. Is more of an issue with the example than with iso itself.
