### ISSUE TITLE
How to handle concurrency on the server?

### ISSUE THREAD

**Issue by coodoo** [goatslacker/iso#14]
Take 'iso-todomvc' for example, what if there are multiple requests to the server at almost the same time, wouldn't the store be polluted or overridden by each work-in-process request?

Example: https://github.com/goatslacker/iso/blob/master/examples/iso-todomvc/server.js#L20

**Comment by goatslacker** [comment]
No because the bootstrap and render process is synchronous so once the data comes back you're guaranteed to render that set and only that set fresh. Once a new request comes in it'll override the previous one that already rendered.

**Comment by coodoo** [comment]
What if I'm in the middle of handling first request (fetching data synchronously) when the 2nd request comes in?

**Comment by goatslacker** [comment]
The data fetching is asynchronous and multiple requests can be in flight. Once the request comes in the bootstrap to flux stores and rendering is synchronous meaning no other task will interrupt it before it's done.

**Comment by coodoo** [comment]
So if two requests completed fetching data at almost the same time and want to bootstrap the store, they will be executed one after the other?

In other words, can I be confident that there won't be collisions between tens and thousands of requests?

**Comment by goatslacker** [comment]
Yes exactly. 

You can be pretty confident, we are running this in production right now serving lots of requests.

**Comment by coodoo** [comment]
Perfect, thanks for the answers!
