### ISSUE TITLE
Website breaking after updating to 5.0.0

### ISSUE THREAD

**Issue by xavimb** [goatslacker/iso#24]
After updating to 5.0.0, I get a bug every time there's some `</script>` text in my data.
Previously that data was inside a div and there were no problems, but now that the data goes inside a `<script>` element as JSON, if there's some text that contains `</script>` the browser considers it's the end of the tag, and it breaks the whole website.

Has anyone experienced the same?

**Comment by ovaris** [comment]
+1

**Comment by goatslacker** [comment]
Ouch. You should definitely be escaping the text you send down. Previously it was being escaped for you but it would increase the size of the payload sent down.

You can put it back in a div pretty easily by providing your own rendering function.

**Comment by xavimb** [comment]
I think this should be documented, it could lead to XSS vulnerability for those who were relying on the data being escaped. Thanks for the help.

**Comment by goatslacker** [comment]
28335eedf3de9fcef001af2c60aab12b5beb821a
