### ISSUE TITLE
Have static method on React Components for pre-fetching?

### ISSUE THREAD

**Issue by iam4x** [goatslacker/iso#4]
Hello @goatslacker,

Instead of making a request for fetching data before server-side render into the `app.use` like in your example:

```
getNameFromServer(function (name) {
  res.locals.data = {
    HelloStore: { name: name }
  }
  next()
})
```

(That means double-work, one method in component / stores for fetching data when app is running client-side, and one on the server-side. Or am I wrong and I didn't understand something?)

Would it possible to have static method on components that would be resolved before rendering, like https://github.com/ericclemmons/react-resolver/ is doing?

Anyway, thank's for Alt & iso :)

**Comment by goatslacker** [comment]
`iso` doesn't have an opinion on how you load your data. It's just a helper function that lets you transfer JSON data from server to client.

I don't know in much detail but I believe react-resolver returns promises, if that's the case then yes you can use react-resolver to declare your data fetching needs at the component level.

**Comment by iam4x** [comment]
Okey thank's for the precision!
