### ISSUE TITLE
Browserify not specified as a dependency

### ISSUE THREAD

**Issue by appsforartists** [goatslacker/iso#6]
Following the iso-react-router-flux instructions (`npm install; npm run build; npm start`) fails:

```
> iso-react-router-flux@1.0.0 build ~/Desktop/iso/examples/react-router-flux
> browserify -t [reactify --harmony] js/client.js > js/bundle.js

sh: browserify: command not found
```

**Comment by goatslacker** [comment]
Good call. Feel free to send a PR otherwise I'll tackle this once I'm online.

**Comment by goatslacker** [comment]
Just checked the package.json and it's defined: https://github.com/goatslacker/iso/blob/master/examples/react-router-flux/package.json#L22

**Comment by appsforartists** [comment]
I don't think I realized there were nested `package.json`s.  I'll have to try again in the morning.

**Comment by goatslacker** [comment]
No worries, yeah the example is supposed to be standalone.
