### ISSUE TITLE
Leave markup without state/meta alone

### ISSUE THREAD

**Issue by ericclemmons** [goatslacker/iso#7]
``` javascript
const iso = new Iso();

iso.add('<!DOCTYPE html>');

this.body = iso.render();
```

produces:

``` html
<div class="___iso-html___" data-key="0"><!DOCTYPE html></div>
<div class="___iso-state___" data-key="0" data-meta="{}" data-state="{}"></div>
```

This is because of:

> https://github.com/goatslacker/iso/blob/feac66165c82d3f6d77eac17d0068b2ac86fd278/src/iso.js#L20-L30

My recommendation is that `<!DOCTYPE html>` is produced without wrapping.  (Similarly, whitespace can be trimmed from the output).

There shouldn't be a need to worry about changing key indexes or anything...

Thoughts?

**Comment by goatslacker** [comment]
Iso is meant to be used to wrap whatever content you want to render that needs JS to bootstrap. Document types, scripts, stylesheets, etc...should be rendered elsewhere.

``` js
const iso = new Iso();

iso.add(someMarkupYouCreate);

this.body = `<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    ${iso.render()}
  </body>
</html>`;
```

I can't think of how to cleanly exclude document type without having to also worry about the other cases and I don't want this to turn into a giant library. Perhaps this can be a separate utility that handles rendering the whole document.

Do you have any ideas on how this could work?

**Comment by ericclemmons** [comment]
lol.

Guess what I just wrote after opening this issue?

``` javascript
    iso.add(React.renderToString(<Layout />), state, meta);

    this.body = `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8">
        </head>
        <body id="app">
          ${iso.render()}
        </body>
      </html>
    `;
```

I was thinking of wrapping the code here with a check on `if (!Object.keys(state[i]).length && !Object.keys(meta[i]).length)` and just returning `markup` as-is (since there was nothing to bootstrap).

> https://github.com/goatslacker/iso/blob/feac66165c82d3f6d77eac17d0068b2ac86fd278/src/iso.js#L20-L30

It it works, would you be open to that?  It would remove superfluous wrappers when there's no `state` / `meta` to bootstrap...

**Comment by ericclemmons** [comment]
On another note, as a neat FYI, I'm trying out streams from Webpack to dynamically generate the `<script>` and `<link>` tags per-render via React (based on the matching routes).

This way, the bundling process is optimized per-route, rather than 1 giant JS + CSS.

**Comment by goatslacker** [comment]
Is there a reason you're not passing in any state/markup using iso?

As for the webpack streams -- ooo I'd love to see an example of that.

**Comment by ericclemmons** [comment]
Oh, I am!  I was using `iso.add(...)` to compose both static (e.g. `<!DOCTYPE html>`) & stateful markup from React.

``` javascript
iso.add(myDoctype);
iso.add(fs.readFileSync('header.html'));
iso.add(React.renderToString(<Layout />), state, meta);
iso.add(fs.readFileSync('analytics.html'));
iso.add(fs.readFileSync('footer.html'));
```

I suppose this is total bikeshedding.  I was just wondering if it even made sense to wrap markup that wasn't going to be bootstrapped at all...

**Comment by goatslacker** [comment]
Oh no, not at all. Iso is just meant to render the stateful parts not render everything :)

Should it render anything else? There can be another method for that perhaps

**Comment by ericclemmons** [comment]
I withdraw my comment :)  Just curious if I was over-utilizing it and, l like most of your projects, I was :D
