### ISSUE TITLE
layout consequences of wrapping the application in a div

### ISSUE THREAD

**Issue by necolas** [goatslacker/iso#9]
Might be worth documenting the HTML that iso generates because it looks like I'll need to style it.

For example, I have a flexbox-based layout that expects `html` and `body` to be 100% high. The app is then grown to fill that space. But since iso wraps the html – `div.___iso-html___` – the layout breaks…unless that iso wrapper is styled to be 100% high too.

Or, iso could allow an extra class to be set so that things don't break if that classname is ever altered in this module.

What do you think?

**Comment by goatslacker** [comment]
I like the extra classes to be set as an option. If you want to submit a PR we can merge it in.

What about the state though? Should that be a <meta /> tag then? Do we customize that one as well? With the same class or a different one?

**Comment by michaelBenin** [comment]
Also related to this issue, I'm trying to use one template language for my isomoprhic react app with express.

With iso, the opening of my app, looks like this:

```
<div class="___iso-html___" data-key="0">
<!doctype>
<html data-reactid=".199oid7moe8" data-react-checksum="1741068151">
...
```

The closing looks like this:

```
</html>
</div>
<div class="___iso-state___" data-key="0" data-meta="{}" data-state="&quot;{\&quot;RepoDetailsStore\&quot;:{\&quot;repo\&quot;:{}}}&quot;">
</div>
```

Currently templates that contain <html> tag do not work with iso.

**Comment by michaelBenin** [comment]
@goatslacker how do you feel about the wrapper element also be set as an option?

**Comment by michaelBenin** [comment]
I'd also like to investigate just using a wrapper element.

**Comment by michaelBenin** [comment]
@necolas does this satisfy your requirements? Can this issue be closed?

I started work on actually removing the wrapper entirely but ran into some issues.

**Comment by Satyam** [comment]
May I suggest that the data portion of the markup (`__iso_state__`) be enclosed in a `<script type="application/json">` tag?  

Script tags with an explicit type which is not recognized as executable simply lie there and they don't take any space within the layout.  The JSON would not go into a `data-xxx` attribute but in the `innerHTML`. Other information can still go into `data-xxx` attributes.

Besides, sending JSON data with its proper mime-type sounds like the proper thing to do and it may allow DOM inspectors to format it more clearly. At least it would have a hint on how to do it.

**Comment by scvnathan** [comment]
+1 Satyam
Having data in a script tag makes way more sense to me. I never understood why it was put inside a div in the first place. And it would remove any issues with layout

**Comment by goatslacker** [comment]
That sounds like a good call. Lets make that change.

**Comment by ninjasort** [comment]
I'm running into a similar issue as @michaelBenin. I'm trying to use a root html React component with React Router to render my app isomorphically versus needing to inject iso.render() markup in a server template. 

What are your thoughts on adding some sort of hook inside the markup being passed into `iso.render` so that it can be injected (html/state script) inside of those hooks? This would allow us to use the root `<html>` react component and only need to prepend a `<!doctype html>` string.

**Comment by ninjasort** [comment]
Created a PR attempting to address this issue. #21 Review would be appreciated. :+1:
